services:
  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

  adapter:
    build: ./adapter
    container_name: adapter
    depends_on:
      - influxdb
    environment:
      - MQTT_DATA_TOPIC=${ADAPTER_MQTT_DATA_TOPIC}
      - MQTT_ALARM_TOPIC=${ADAPTER_MQTT_ALARM_TOPIC}
      - MQTT_SILENCE_TOPIC=${ADAPTER_MQTT_SILENCE_TOPIC}
      - MQTT_SERVER_ADDRESS=${ADAPTER_MQTT_SERVER_ADDRESS}
      - MQTT_SERVER_PORT=${ADAPTER_MQTT_SERVER_PORT}
      - INFLUX_ADDRESS=${ADAPTER_INFLUX_ADDRESS}
      - INFLUX_PORT=${ADAPTER_INFLUX_PORT}
      - INFLUX_USER=${ADAPTER_INFLUX_USER}
      - INFLUX_TOKEN=${ADAPTER_INFLUX_TOKEN}
      - INFLUX_ORG=${ADAPTER_INFLUX_ORG}
      - INFLUX_BUCKET=${ADAPTER_INFLUX_BUCKET}

volumes:
  influxdb-storage:
  grafana-storage:
