{
 "title": "Greenhouse",
 "description": "Environmental values of the greenhouse",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Humidity inside the greenhouse",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"pser_umu_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"env\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")"
    }
   ]
  },
  {
   "title": "Light intensity",
   "type": "timeseries",
   "description": "Light intensity inside the greenhouse",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"pser_umu_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"env\")\n  |> filter(fn: (r) => r[\"_field\"] == \"light\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature inside the greenhouse",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"pser_umu_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"env\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")"
    }
   ]
  }
 ]
}